export interface Product {
  id: string
  name: string
  slug: string
  category: string
  price: number
  originalPrice?: number
  description: string
  longDescription: string
  image: string
  badge?: string
  rating: number
  reviews: number
  inStock: boolean
  features: string[]
}

export interface CartItem extends Product {
  quantity: number
}

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  icon: string
  color: string
  gradient: string
  productCount: number
}

export const categories: Category[] = [
  {
    id: 'fireworks',
    name: 'Fireworks',
    slug: 'fireworks',
    description: 'Spectacular professional-grade fireworks for every celebration',
    icon: '🎆',
    color: '#f59e0b',
    gradient: 'from-orange-500 to-red-600',
    productCount: 12,
  },
  {
    id: 'helium-balloons',
    name: 'Helium Balloons',
    slug: 'helium-balloons',
    description: 'Beautiful balloon arrangements and helium gas for all occasions',
    icon: '🎈',
    color: '#ec4899',
    gradient: 'from-pink-500 to-purple-600',
    productCount: 15,
  },
  {
    id: 'ice-fountains',
    name: 'Ice Fountains',
    slug: 'ice-fountains',
    description: 'Indoor sparkler-style fountains for birthday cakes and celebrations',
    icon: '✨',
    color: '#3b82f6',
    gradient: 'from-blue-400 to-cyan-500',
    productCount: 8,
  },
  {
    id: 'smoke-flares',
    name: 'Smoke Flares',
    slug: 'smoke-flares',
    description: 'Colourful smoke bombs perfect for photoshoots and events',
    icon: '💨',
    color: '#8b5cf6',
    gradient: 'from-purple-500 to-indigo-600',
    productCount: 10,
  },
  {
    id: 'perfumes',
    name: 'Perfumes',
    slug: 'perfumes',
    description: 'Premium fragrances and luxury perfumes at unbeatable prices',
    icon: '🌸',
    color: '#f43f5e',
    gradient: 'from-rose-400 to-pink-600',
    productCount: 20,
  },
  {
    id: 'gifts',
    name: 'Gifts & Cards',
    slug: 'gifts',
    description: 'Thoughtful gifts, novelties, and greeting cards for all occasions',
    icon: '🎁',
    color: '#10b981',
    gradient: 'from-emerald-400 to-teal-600',
    productCount: 25,
  },
]

export const products: Product[] = [
  // Fireworks
  {
    id: 'fw-001',
    name: 'Golden Rain Fountain',
    slug: 'golden-rain-fountain',
    category: 'fireworks',
    price: 14.99,
    originalPrice: 19.99,
    description: 'Stunning golden sparks raining down for 60 seconds of pure magic',
    longDescription: 'The Golden Rain Fountain is our bestselling outdoor firework. Producing a magnificent shower of golden sparks that cascade like rain for a full 60 seconds. Perfect for garden parties, weddings, and celebrations. Suitable for use on grass or hard surfaces.',
    image: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600&q=80',
    badge: 'Bestseller',
    rating: 4.8,
    reviews: 124,
    inStock: true,
    features: ['60 second display', 'Golden sparks', 'Outdoor use', 'Easy ignition', 'Safe distance: 5m'],
  },
  {
    id: 'fw-002',
    name: 'Colour Burst Cake',
    slug: 'colour-burst-cake',
    category: 'fireworks',
    price: 24.99,
    description: 'Multi-shot barrage with 36 shots of vivid multicolour stars',
    longDescription: 'The Colour Burst Cake delivers 36 rapid-fire shots of vibrant multicoloured stars, crackling effects, and golden tails. One of our most popular cake fireworks for a reason — it fills the sky with pure colour.',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
    badge: 'New',
    rating: 4.9,
    reviews: 87,
    inStock: true,
    features: ['36 shots', 'Multicolour stars', 'Crackling effects', 'Outdoor use', 'Safe distance: 8m'],
  },
  {
    id: 'fw-003',
    name: 'Sparkler Bundle (20pk)',
    slug: 'sparkler-bundle',
    category: 'fireworks',
    price: 6.99,
    description: 'Classic sparklers — 20 pack, perfect for birthdays and parties',
    longDescription: 'No party is complete without sparklers! Our classic 30cm sparklers burn brightly for approximately 60 seconds each. Safe and fun for all ages (adult supervision required). Ideal for photos, birthdays, and New Year celebrations.',
    image: 'https://images.unsplash.com/photo-1577048982768-5cb3e7ddfa23?w=600&q=80',
    rating: 4.7,
    reviews: 210,
    inStock: true,
    features: ['20 sparklers per pack', '30cm length', '~60 second burn', 'Classic silver effect', 'Ideal for photos'],
  },
  {
    id: 'fw-004',
    name: 'Rockets Triple Pack',
    slug: 'rockets-triple-pack',
    category: 'fireworks',
    price: 18.99,
    originalPrice: 22.99,
    description: 'Three powerful rockets with coloured stars and loud reports',
    longDescription: 'Our Rockets Triple Pack gives you three launches of skyward spectacle. Each rocket soars to 40 metres before bursting into coloured stars with a satisfying bang. Mix of red, green, and gold effects.',
    image: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=600&q=80',
    badge: 'Sale',
    rating: 4.6,
    reviews: 65,
    inStock: true,
    features: ['3 rockets included', '40m altitude', 'Mixed colour effects', 'Outdoor use only', 'Launch tube included'],
  },
  // Helium Balloons
  {
    id: 'hb-001',
    name: 'Foil Number Balloons',
    slug: 'foil-number-balloons',
    category: 'helium-balloons',
    price: 8.99,
    description: 'Giant gold or silver foil number balloons — any number available',
    longDescription: 'Make an age the centrepiece of your party! Our giant foil number balloons (40 inch) can be filled with helium for a floating display or air-filled for table displays. Choose from gold, silver, or rose gold. Specify your number at checkout.',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&q=80',
    badge: 'Popular',
    rating: 4.9,
    reviews: 342,
    inStock: true,
    features: ['40 inch size', 'Gold, silver, rose gold', 'Helium or air fill', 'Any number 0-9', 'Ribbon included'],
  },
  {
    id: 'hb-002',
    name: 'Latex Balloon Bouquet (12pk)',
    slug: 'latex-balloon-bouquet',
    category: 'helium-balloons',
    price: 12.99,
    description: 'Vibrant latex balloons pre-filled with helium, ready to float',
    longDescription: 'Our helium-filled latex balloon bouquets come in a stunning array of colours. Each pack of 12 balloons floats for up to 24 hours and comes tied with matching ribbon. Choose your colour theme at checkout.',
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&q=80',
    rating: 4.7,
    reviews: 189,
    inStock: true,
    features: ['12 balloons included', 'Pre-filled with helium', 'Float time ~24 hours', 'Ribbon included', 'Choice of colours'],
  },
  {
    id: 'hb-003',
    name: 'Giant Confetti Balloon',
    slug: 'giant-confetti-balloon',
    category: 'helium-balloons',
    price: 5.99,
    description: 'Clear 36-inch balloon stuffed with colourful confetti',
    longDescription: 'Our giant clear confetti balloons create a stunning visual effect. Filled with helium and stuffed with gold, silver, or mixed confetti. Each balloon is 36 inches when inflated and floats for up to 48 hours.',
    image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&q=80',
    badge: 'Trending',
    rating: 4.8,
    reviews: 156,
    inStock: true,
    features: ['36 inch clear balloon', 'Helium filled', 'Confetti stuffed', '48 hour float', 'Multiple confetti options'],
  },
  {
    id: 'hb-004',
    name: 'Helium Gas Canister',
    slug: 'helium-gas-canister',
    category: 'helium-balloons',
    price: 34.99,
    originalPrice: 39.99,
    description: 'Disposable helium canister — fills up to 30 standard balloons',
    longDescription: 'Our helium gas canisters are perfect for filling your own balloons at home. Each canister fills approximately 30 standard 11-inch latex balloons or 10 foil balloons. Includes easy nozzle attachment.',
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&q=80',
    rating: 4.6,
    reviews: 98,
    inStock: true,
    features: ['Fills 30 latex balloons', 'Or 10 foil balloons', 'Easy-use nozzle', 'Disposable canister', 'Safe for home use'],
  },
  // Ice Fountains
  {
    id: 'if-001',
    name: 'Birthday Cake Fountains (6pk)',
    slug: 'birthday-cake-fountains',
    category: 'ice-fountains',
    price: 9.99,
    description: 'Indoor sparkler fountains perfect for birthday cakes — 6 pack',
    longDescription: 'Transform any birthday cake into a spectacular showpiece with our indoor ice fountains. Each fountain produces a gorgeous 25cm shower of cold sparks for approximately 45 seconds. Completely safe for indoor use. Simply insert into the cake and light!',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 445,
    inStock: true,
    features: ['6 fountains per pack', '45 second burn', '25cm height', 'Indoor safe', 'Cold spark technology'],
  },
  {
    id: 'if-002',
    name: 'Stage Effect Fountains (4pk)',
    slug: 'stage-effect-fountains',
    category: 'ice-fountains',
    price: 19.99,
    description: 'Professional-grade indoor fountains for stage and event use',
    longDescription: 'Our stage-effect ice fountains are designed for professional use at events, performances, and large celebrations. Each fountain produces a 60cm shower of cold sparks for 60 seconds. Perfect for wedding first dances and stage entrances.',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80',
    badge: 'Pro',
    rating: 4.8,
    reviews: 67,
    inStock: true,
    features: ['4 fountains per pack', '60 second display', '60cm height', 'Stage safe', 'Professional grade'],
  },
  // Smoke Flares
  {
    id: 'sf-001',
    name: 'Rainbow Smoke Bomb Set',
    slug: 'rainbow-smoke-bomb-set',
    category: 'smoke-flares',
    price: 22.99,
    description: 'Set of 7 colourful smoke bombs — one of each colour of the rainbow',
    longDescription: 'Our Rainbow Smoke Bomb Set gives you one each of red, orange, yellow, green, blue, indigo, and violet smoke bombs. Perfect for gender reveals, photoshoots, festivals, and events. Each bomb produces a vibrant cloud of colour for 60-90 seconds.',
    image: 'https://images.unsplash.com/photo-1533928298208-27ff66555d8d?w=600&q=80',
    badge: 'Fan Favourite',
    rating: 4.9,
    reviews: 203,
    inStock: true,
    features: ['7 smoke bombs included', 'All 7 rainbow colours', '60-90 second smoke', 'Photoshoot perfect', 'Pull-ring ignition'],
  },
  {
    id: 'sf-002',
    name: 'Gender Reveal Smoke Cannon',
    slug: 'gender-reveal-smoke-cannon',
    category: 'smoke-flares',
    price: 15.99,
    description: 'Pink or blue smoke cannon for the perfect gender reveal moment',
    longDescription: 'Make your gender reveal unforgettable with our smoke cannon. Simply pull the ripcord for a dramatic blast of either pink (girl) or blue (boy) smoke. Specify your colour choice at checkout. Suitable for outdoor use.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80',
    badge: 'Trending',
    rating: 4.8,
    reviews: 178,
    inStock: true,
    features: ['Pink or blue options', 'Ripcord activation', 'Dramatic effect', 'Outdoor use', 'Single use'],
  },
  // Perfumes
  {
    id: 'pf-001',
    name: 'Oud & Rose Eau de Parfum',
    slug: 'oud-rose-eau-de-parfum',
    category: 'perfumes',
    price: 29.99,
    originalPrice: 45.00,
    description: 'Rich oriental fragrance blending oud wood with velvety rose — 100ml',
    longDescription: 'A luxurious oriental fragrance that opens with Bulgarian rose and transitions to a deep heart of oud wood. The base notes of amber and musk create a warm, long-lasting sillage. Perfect for evening occasions and gifting.',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80',
    badge: 'Luxury Pick',
    rating: 4.8,
    reviews: 92,
    inStock: true,
    features: ['100ml bottle', 'Eau de Parfum', 'Oriental fragrance', 'Long-lasting', 'Elegant gift box'],
  },
  {
    id: 'pf-002',
    name: 'Floral Fantasy Body Mist',
    slug: 'floral-fantasy-body-mist',
    category: 'perfumes',
    price: 12.99,
    description: 'Light and fresh floral body mist with notes of jasmine and peach — 200ml',
    longDescription: 'A fresh and feminine body mist perfect for everyday wear. Notes of jasmine, white peach, and fresh citrus make this a delightfully uplifting fragrance. Great as a gift or personal treat.',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80',
    rating: 4.6,
    reviews: 143,
    inStock: true,
    features: ['200ml bottle', 'Body mist formula', 'Floral & fruity', 'Light formula', 'Everyday wear'],
  },
  // Gifts
  {
    id: 'gf-001',
    name: 'Party Hamper Deluxe',
    slug: 'party-hamper-deluxe',
    category: 'gifts',
    price: 49.99,
    originalPrice: 65.00,
    description: 'The ultimate party gift hamper — packed with treats and surprises',
    longDescription: 'Our Deluxe Party Hamper is the ultimate celebration gift. Packed with party poppers, mini sparklers, confetti, a bottle of bubbly, chocolates, and personalised greeting card. Presented in a beautiful gift box with ribbon.',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    badge: 'Gift Idea',
    rating: 4.9,
    reviews: 78,
    inStock: true,
    features: ['Everything included', 'Gift boxed', 'Personalised card', 'Bubbly included', 'Next day delivery'],
  },
  {
    id: 'gf-002',
    name: 'Luxury Greeting Cards (5pk)',
    slug: 'luxury-greeting-cards',
    category: 'gifts',
    price: 7.99,
    description: 'Premium quality greeting cards for birthdays, weddings, and all occasions',
    longDescription: 'Our luxury greeting card packs feature stunning foil-embossed designs suitable for birthdays, weddings, anniversaries, and more. Each card comes with a matching envelope. Set of 5 mixed occasion cards.',
    image: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80',
    rating: 4.7,
    reviews: 234,
    inStock: true,
    features: ['5 cards per pack', 'Foil embossed', 'Mixed occasions', 'Envelopes included', 'Premium quality'],
  },
  {
    id: 'gf-003',
    name: 'Personalised Photo Frame',
    slug: 'personalised-photo-frame',
    category: 'gifts',
    price: 18.99,
    description: 'Beautiful personalised photo frame — perfect keepsake gift',
    longDescription: 'A timeless gift for any occasion. Our personalised photo frame can be engraved with a name, date, or message. Available in silver or gold finish, accommodating 6x4 or 5x7 inch photos.',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80',
    badge: 'Personalised',
    rating: 4.8,
    reviews: 156,
    inStock: true,
    features: ['Personalised engraving', 'Silver or gold finish', '6x4 or 5x7 size', 'Gift wrapped', 'Keepsake quality'],
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Priya Sharma',
    location: 'Wembley',
    rating: 5,
    text: 'Absolutely fantastic shop! Bought fireworks and ice fountains for my daughter\'s 18th birthday. The ice fountains on the cake were a massive hit — everyone was amazed. Will definitely be back!',
    occasion: 'Birthday Party',
  },
  {
    id: 2,
    name: 'Mohammed Ali',
    location: 'Southall',
    rating: 5,
    text: 'Best party shop in West London by far. The staff are so helpful and knowledgeable. Got smoke bombs for our gender reveal and the photos turned out incredible. 100% recommend!',
    occasion: 'Gender Reveal',
  },
  {
    id: 3,
    name: 'Sarah Thompson',
    location: 'Ealing',
    rating: 5,
    text: 'I\'ve been coming here for years — before a big family gathering or wedding, this is always my first stop. The helium balloon arrangements they put together were beautiful. Great prices too!',
    occasion: 'Wedding',
  },
  {
    id: 4,
    name: 'Rakesh Patel',
    location: 'Harrow',
    rating: 5,
    text: 'What a shop! It\'s a shame the location isn\'t on a busier high street — it should be in Kensington! Gifts, party supplies, fireworks, perfumes — you name it, they have it. Prices are very reasonable.',
    occasion: 'Diwali Celebration',
  },
]
